# vim: set ts=2 sts=2 sw=2 expandtab :
dist: xenial
sudo: required
language: bash
services:
  - docker

before_install:
  - sudo apt-get install -y python3-pip python3-setuptools
  - sudo pip3 install --upgrade pip
  - sudo pip install PyGithub
  - curl -Ls -o docker-build https://github.com/mate-desktop/mate-dev-scripts/raw/master/travis/docker-build
  - chmod +x docker-build

install:
  - ./docker-build --name ${DISTRO} --config .travis.yml --install

script:
  - ./docker-build --name ${DISTRO} --verbose --config .travis.yml --build autotools

deploy:
  - provider: script
    script: ./docker-build --verbose --config .travis.yml --release github
    skip_cleanup: true
    on:
      tags: true
      condition: "${TRAVIS_TAG} =~ ^v.*$ && ${DISTRO} =~ ^fedora.*$"

env:
  - DISTRO="archlinux/base"
  - DISTRO="debian:testing"
  - DISTRO="fedora:30"
  - DISTRO="ubuntu:19.04"

##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    # Useful URL: https://git.archlinux.org/svntogit/community.git/tree/engrampa
    - caja
    - file
    - gcc
    - git
    - gtk3
    - intltool
    - json-glib
    - make
    - mate-common
    - which
    - yelp-tools

  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/engrampa
    - gettext
    - git
    - intltool
    - libcaja-extension-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libjson-glib-dev
    - libmagic-dev
    - make
    - mate-common
    - yelp-tools

  fedora:
    # Useful URL: https://src.fedoraproject.org/cgit/rpms/engrampa.git
    - caja-devel
    - desktop-file-utils
    - file-devel
    - gcc
    - git
    - gtk3-devel
    - json-glib-devel
    - libSM-devel
    - make
    - mate-common
    - redhat-rpm-config

  ubuntu:
    - gettext
    - git
    - intltool
    - libcaja-extension-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libjson-glib-dev
    - libmagic-dev
    - make
    - mate-common
    - yelp-tools

variables:
  - CFLAGS="-Wall -Werror=format-security"

before_scripts:
  - if [ ${DISTRO_NAME} == "debian" ];then
  -     curl -Ls -o debian.sh https://github.com/mate-desktop/mate-dev-scripts/raw/master/travis/debian.sh
  -     bash ./debian.sh
  - fi

after_scripts:
  - make distcheck

releases:
  draft: false
  prerelease: false
  checksum: true
  file_glob: true
  files: engrampa-*.tar.xz
  github_release:
    tags: true
    overwrite: true
    base_version: 1.20.0
    notify_servers:
      - https://release.mate-desktop.org/release
